//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ice_cream_parlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_buy
    {
        public int buy_id { get; set; }
        public string b_name { get; set; }
        public string b_contact { get; set; }
        public string b_add { get; set; }
        public string b_cost { get; set; }
        public string b_paying { get; set; }
    }
}
