//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ice_cream_parlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string u_pwd { get; set; }
        public string u_subs { get; set; }
    }
}
