//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ice_cream_parlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback
    {
        public int f_id { get; set; }
        public string f_name { get; set; }
        public string f_email { get; set; }
        public string f_icecream { get; set; }
        public string f_feedBack { get; set; }
    }
}
